---
name: docker-push

# yamllint disable-line rule:truthy
on:
  workflow_run:
    workflows: ["lint"]
    types:
      - completed

jobs:
  push-enabled:
    name: push-enabled
    runs-on: ubuntu-20.04
    outputs:
      push-enabled: ${{ steps.check.outputs.push-enabled }}
    steps:
      - name: Check if push allowed
        id: check
        run: |
          push_enabled=false
          if [[ ${{ github.event.workflow_run.head_branch }} =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "Detected semver tag"
            push_enabled=true
          elif [[ $head_branch == "master" ]]; then
            echo "Detected master branch"
            push_enabled=true
          else
            echo "Unable to detect semver tag or master branch"
            push_enabled=false
          fi

          if [[ ${{ github.event.workflow_run.conclusion }} != 'success' ]]; then
            echo "Unable to detect successful lint workflow_run conclusion"
            push_enabled=false
          fi

          echo "::set-output name=push-enabled::${push_enabled}"


  docker-push:
    name: push latest
    runs-on: ubuntu-20.04
    # yamllint disable-line rule:line-length
    needs: push-enabled
    if: needs.push-enabled.outputs.push-enabled == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate docker metadata
        id: docker_meta
        # yamllint disable-line rule:line-length
        uses: crazy-max/ghaction-docker-meta@c53f88523ad1fcebbdb10b3bb9cfa7ddb69d6677  # v1.8.5 => c53f88523ad1fcebbdb10b3bb9cfa7ddb69d6677
        with:
          images: dokku/ci-docker-image
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
