---
name: push

# yamllint disable-line rule:truthy
on:
  workflow_run:
    workflows: ["lint"]
    branches:
      - master
    types:
      - completed

jobs:
  build:
    name: push latest
    runs-on: ubuntu-20.04
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      # yamllint disable-line rule:line-length
      - uses: haya14busa/action-workflow_run-status@967ed83efa565c257675ed70cfe5231f062ddd94
        # v1.0.0 => 967ed83efa565c257675ed70cfe5231f062ddd94
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dokku/ci-image:latest
      - name: Update repo description
        uses: peter-evans/dockerhub-description@1d0dd5623cbe23a2d92d8cbc6d3977a7e1c96b0d
        # v2.4.1 => 1d0dd5623cbe23a2d92d8cbc6d3977a7e1c96b0d
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: dokku/ci-image
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
